name: rest_client
description: A Dart implementation of the a REST client that supports using an Isolate for decoding.
version: 2.0.0
homepage: https://github.com/peiffer-innovations/rest_client

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.0
  intl: ^0.17.0
  json_class: ^2.0.0
  logging: ^1.0.0
  meta: ^1.3.0
  uuid: ^3.0.1

dev_dependencies:
  test: any
